SELECT GETDATE(); -- Current date
SELECT DATEADD(YEAR, -5, GETDATE()); -- 5 years ago
SELECT DATEDIFF(MINUTE,  DATEADD(YEAR, -5, GETDATE()), GETDATE()); -- Positive
SELECT DATEDIFF(MINUTE, GETDATE(),  DATEADD(YEAR, -5, GETDATE())); -- Negative